### ISSUE TITLE
Nuget site text for this version

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-5.472#3]
Small issue, nuget text needs to state .net 4.7**2**
![image](https://user-images.githubusercontent.com/2418812/51427003-f5ff7400-1be9-11e9-8f84-a4dae52402d6.png)

**Comment by Wagnerp** [comment]
Yes I noticed that, I'll need to artificially bump the build number to 717 to fix it, as the NuGet website lacks page editing tools.
