### ISSUE TITLE
Strange Borders at KryptonForm when using KryptonRibbon

### ISSUE THREAD

**Issue by richterAl** [Wagnerp/Krypton-NET-5.472#5]
Hello everybody,

I'm working on program that uses the KryptonToolkit and the KryptonRibbon.
I've got strange borders on the bottom and the right side of the form when using KryptonRibbon on it.
This issue is not present without the KryptonRibbon.

This issue was **not** present in the repository ComponentFactory/Krypton.git

![grafik](https://user-images.githubusercontent.com/47531703/52574961-ad6c5c80-2e1d-11e9-9f33-4c8679f0a9bb.png)

OS: Win 10 1809 (17763.292)

Have you any solutions for this issue?

Best regards

**Comment by Wagnerp** [comment]
Hi @richterAl 

To fix this, you need to set the `UseDropShadow` property on the `KryptonForm` to **false**. This is set to true by default, but it does not work well if you are using the Ribbon component. Hope this solves your issue.

**Comment by richterAl** [comment]
Hello @Wagnerp,

unfortunately this does not solve the issue, because this property is already set to false.
To reproduce this issue you only need to start the example app [Krypton Ribbon Examples][Ribbon + Navigator + Workspace].

**Comment by Wagnerp** [comment]
Hi @richterAl 

I think that I found the issue. It's not redrawing when `UseDropShadow` is changed.

**Comment by richterAl** [comment]
Hi @Wagnerp,

you are right the shadow cames from the DropShadow.
Beside to the redraw problem I think the implementation is wrong:
CreateParams is called every time when creating the window. But the property has no influence to the parameters.
I think this would be correct:

        protected override CreateParams CreateParams
        {
            get
            {
                // add the drop shadow flag for automatically drawing
                // a drop shadow around the form
                CreateParams cp = base.CreateParams;
                if (_useDropShadow)
                {
                    cp.ClassStyle |= CS_DROPSHADOW;
                }
                return cp;
            }
        }

There is also a mismatch between the DefaultValueAttribute value and the indeed value of `_useDropShadow`: it should be initialized with `true`.

**Comment by Wagnerp** [comment]
Hi @richterAl 

Will look into it, was about a year ago since I last worked on this part of the code.

**Comment by Wagnerp** [comment]
Hi @richterAl 

Good news, it's now fixed! Will upload a new package soon.

**Comment by richterAl** [comment]
Hello @Wagnerp,

this works for me, because I'll will set this property in the desinger. 👍 (prior `CreateHandle` calling) 

But keep in mind that the refresh is not working.
If the value is changed after the handle of the window is created (native) any change on the property do not work.
To apply a new a new ClassStyle a `RecreateHandle` is required (seems to be that Windows does'nt apply the new class style by calling `SetClassLong`). This would mean the window will be complety destroyed by Windows and recreated. But there seems to be a general problem in the Krypton.Toolkit on calling `RecreateHandle` for styling. I ended up on calling the `RecreateHandle` function (malfunction in form painting). I also tyred to use `SetWindowPos` with `FrameChanged` but it did not work. 

Here my tries: 

        internal enum GCL_Flags : int
        {
            GCLP_MENUNAME = -8,
            GCLP_HBRBACKGROUND = -10,
            GCLP_HCURSOR = -12,
            GCLP_HICON = -14,
            GCLP_HMODULE = -16,
            GCL_CBWNDEXTRA = -18,
            GCL_CBCLSEXTRA = -20,
            GCLP_WNDPROC = -24,
            GCL_STYLE = -26,
            GCLP_HICONSM = -34,
            GCW_ATOM = -32
        }
        [DllImport("user32.dll", EntryPoint = "SetClassLong")]
        internal static extern uint SetClassLongPtr32(HandleRef hWnd, GCL_Flags nIndex, uint dwNewLong);

        [DllImport("user32.dll", EntryPoint = "SetClassLongPtr")]
        internal static extern IntPtr SetClassLongPtr64(HandleRef hWnd, GCL_Flags nIndex, IntPtr dwNewLong);

        [DllImport("user32.dll", EntryPoint = "GetClassLong")]
        internal static extern uint GetClassLongPtr32(HandleRef hWnd, GCL_Flags nIndex);

        [DllImport("user32.dll", EntryPoint = "GetClassLongPtr")]
        internal static extern IntPtr GetClassLongPtr64(HandleRef hWnd, GCL_Flags nIndex);

        internal static IntPtr GetClassLongPtr(HandleRef hWnd, GCL_Flags nIndex)
        {
            if (IntPtr.Size > 4)
                return GetClassLongPtr64(hWnd, nIndex);
            else
                return new IntPtr(GetClassLongPtr32(hWnd, nIndex));
        }

        internal static IntPtr SetClassLongPtr(HandleRef hWnd, GCL_Flags nIndex, IntPtr dwNewLong)
        {
            if (IntPtr.Size > 4)
                return SetClassLongPtr64(hWnd, nIndex, dwNewLong);
            else
                return new IntPtr(SetClassLongPtr32(hWnd, nIndex, unchecked((uint)dwNewLong.ToInt32())));
        }

        private void UpdateClassStyle()
        {
            HandleRef __handle = new HandleRef(this, this.Handle);
            
            IntPtr __style = GetClassLongPtr(__handle, GCL_Flags .GCL_STYLE);
            Int64 __stylevalue = __style.ToInt64();

            if (this.UseDropShadow)
            {
                __stylevalue |= CS_DROPSHADOW;
            }
            else
            {
                __stylevalue &= ~CS_DROPSHADOW;
            }
            __style = new IntPtr(__stylevalue);
            SetClassLongPtr(__handle, ClassLongFlags.GCL_STYLE, __style);

            this.RecreateHandle();
        }

        public bool UseDropShadow
        {
            get => _useDropShadow;

            set
            {
                _useDropShadow = value;

                UpdateDropShadowDraw(_useDropShadow);

                if (this.IsHandleCreated)
                {
                    UpdateClassStyle();
                }

            }
        }

**Comment by Wagnerp** [comment]
Hi @richterAl 

Are you trying to change the property by using code?

**Comment by richterAl** [comment]
Hello @Wagnerp,

no I do not. So the current solution works for me.
But I wanted to try to fix the refresh problem, if somebody set this property in code. 
This was only for your information.

**Comment by Wagnerp** [comment]
Hi @richterAl 

Thanks for updating me, I'll try to implement a public method to alter it sometime in the future.
