### ISSUE TITLE
KryptonMessageBox.TopMost

### ISSUE THREAD

**Issue by richterAl** [Wagnerp/Krypton-NET-5.472#6]
Hello everybody,

I'm working on program that uses the KryptonToolkit.
By default the KryptonMessageBox is displayed TopMost, which means it is on the top of any other application. This behavoir is different to the standard MessageBox and all other none .Net programms and I don't like it.

I would like to ask you if it is possible to add a static property TopMost to the KryptonMessageBox class which will be used in InitializeComponent? 
By default this property should be initialized with true to be backward compatible.

Best regards

**Comment by Wagnerp** [comment]
Hi @richterAl 

It might be something worth adding to the more versatile messagebox in the extended toolkit. The one we are are developing there is a lot more customisable, with the ability to set your own font.

**Comment by richterAl** [comment]
This will work for me.

**Comment by Wagnerp** [comment]
Would you mind me closing this thread, and opening the request on https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470?

**Comment by richterAl** [comment]
Yes I will do. No problem.
